# services:
#   web:
#     build: .
#     ports:
#       - "80:80"
#     volumes:
#      - .:/app
#      - ./node_modules:/app/node_modules
#     environment:
#       NODE_ENV: development
#     stdin_open: true
#     tty: true
#     command: npm start

version: '3'
services:
  web:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/your-ecr-repo:latest
    ports:
      - "80:80"
